#!/usr/bin/env php
<?php
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;

        break;
    }
}

use WackyStudio\Flatblog\Core\ApplicationFactory;

$app = (new ApplicationFactory(require(__DIR__ . '/src/dependencies.php')))->boot();
require(__DIR__ . '/src/commands.php');
$app->run();